import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Link from "next/link";
import Head from "next/head";
import NavBar from "./components/navBar/NavBar";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" type="image/png" href="/icon.png" />
      </Head>
      <body className={`${geistSans.variable} ${geistMono.variable}`} style={{backgroundColor: '#80a4938c'}}>
        {/* Navigation Bar */}

        <NavBar />
        {/* Routes */}
        {children}
        
        <Footer />
      </body>
    </html>
  );
}
