import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Link from "next/link";
import Head from "next/head";
import NavBar from "./components/navBar/NavBar";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" type="image/png" href="/icon.png" />
      </Head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Navigation Bar */}
        <nav style={{width: '100%', height: '50px', padding: '1%', display: 'flex', justifyContent:'flex-end', alignItems: 'center', backgroundColor: 'teal' }}>
          <Link href = {'/'} style = {{margin: '30px'}}>Home</Link>
          <Link href = {'/about'} style = {{margin: '30px'}}>About</Link>
          <Link href = {'/projects'} style = {{margin: '30px'}}>Projects</Link>
          <Link href = {'/contact'} style = {{margin: '30px'}}>Contact</Link>
        </nav>
        <NavBar />
        {/* Routes */}
        {children}
        
        <Footer />
      </body>
    </html>
  );
}
